戻るボタンの実装
team-finding-hiko/php-outdoor pull request #6
Opened 2023-10-05 03:50 UTC by finding-hiko

確認画面に戻るボタンの機能を追加しました

<img width="334" alt="スクショ1" src="https://github.com/team-finding-hiko/php-outdoor/assets/118088137/3ed032b9-02fb-4957-acc1-2061c99b569d">
<img width="162" alt="スクショ2" src="https://github.com/team-finding-hiko/php-outdoor/assets/118088137/1834330b-d79d-4401-a629-170046d9f6f9">
<img width="343" alt="スクショ3" src="https://github.com/team-finding-hiko/php-outdoor/assets/118088137/c452a56e-7fa4-4f2e-bc5b-d3dff0eb8dc4">

2023-10-05 04:53 UTC, kolbe-ryo commented on www/html/index.php
> +if (isset($_POST['back']) && $_POST['back']) {
@finding-hiko 
ここの条件判定は何にも使われていないけどどこかで使う予定があるということ？

2023-10-05 04:55 UTC, kolbe-ryo commented on www/html/index.php
> +$mode = 'input';
多分ここの書き方は下記みたいな感じがいい気がする

```
<?php
$mode = '';
if (isset($_POST['back']) && $_POST['back']) {
  $mode = 'input';
} else if (isset($_POST['confirm']) && $_POST['confirm']) {
  $mode = 'confirm';
} else if (isset($_POST['send']) && $_POST['send']) {
  $mode = 'send';
}
?>
```

2023-10-05 04:56 UTC, kolbe-ryo commented on www/html/index.php
> +} else if (isset($_POST['send']) && $_POST['send']) {
@finding-hiko 
ここの書き方って、isset($_POST['confirm']) && $_POST['confirm'] どちらの条件も必要？
どっちがでいい気もするけど

2023-10-05 04:59 UTC, kolbe-ryo requested changes
コメントしましたー
自分仕事してる？w

同じブランチで、指摘事項修正の必要があれば修正してpushしてください。
ちなみに指摘事項1つに対して1つのcommitに分けてね。（今回だと[こちら](https://github.com/team-finding-hiko/php-outdoor/pull/6/files#r1346781980)の修正で1つのcommit, [こちら](https://github.com/team-finding-hiko/php-outdoor/pull/6/files#r1346781508)の指摘対応で1つのcommitみたいに）

2023-10-05 05:00 UTC, kolbe-ryo commented
@finding-hiko 
あと、タスク完了したらhttps://github.com/team-finding-hiko/php-outdoor/issuesのチェックつけていってねー

2023-10-08 06:16 UTC, finding-hiko commented on www/html/index.php
> +$mode = 'input';
@kolbe-ryo 
デフォルトとして入力画面をinputにしたい為、最初の書き方にしております。
[a56ca77](https://github.com/team-finding-hiko/php-outdoor/pull/6/commits/a56ca773fdeaff5dd50ddc0ce6fccf8d1edc0fca)

2023-10-08 06:16 UTC, finding-hiko commented on www/html/index.php
> +} else if (isset($_POST['send']) && $_POST['send']) {
@kolbe-ryo 
おそらくどちらも必要かと思いますが、確認した上で、後ほど処理内容記述させて頂きます。
[f2641b6](https://github.com/team-finding-hiko/php-outdoor/pull/6/commits/f2641b686c5ab593b1f2777c7d9658fb75aa4eee)

2023-10-08 06:17 UTC, kolbe-ryo commented on www/html/index.php
> +} else if (isset($_POST['send']) && $_POST['send']) {
@finding-hiko 
承知ですー

2023-10-08 06:17 UTC, kolbe-ryo commented on www/html/index.php
> +$mode = 'input';
@finding-hiko 
OKです！

2023-10-08 06:18 UTC, kolbe-ryo approved these changes
👍

2023-10-08 06:19 UTC, merged